//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сессия_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entities
    {
        public string Ent_ID { get; set; }
        public string Ent_Name { get; set; }
        public int Ent_Measures { get; set; }
        public int Ent_Price { get; set; }
        public int Ent_Max_Sale { get; set; }
        public int Ent_Man { get; set; }
        public int Ent_Del { get; set; }
        public int Ent_Cat { get; set; }
        public float Ent_True_Sale { get; set; }
        public int Ent_Warehouse { get; set; }
        public string Ent_Desc { get; set; }
        public string Ent_Img { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Deliverer Deliverer { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Measures Measures { get; set; }
    }
}
